apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azuredocs-updates-utils
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azuredocs-updates-utils
    spec:
      containers:
      - name: azuredocs-updates-utils
        image: oliverlo.azurecr.io/azuredocs-updates-utils:1.0.5
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azuredocs-updates-utils
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azuredocs-updates-utils
